config/routes.rb
BusTimetable::Application.routes.draw do
  resources :lines, :except => [:new]
  resources :stations, :except => [:new]
  resources :stops, :except => [:new]
end

app/models/line.rb
class Line < ActiveRecord::Base
  validates :line_number, presence:true
  has_many :stops
  has_many :stations, through: :stops

  def show_lines
    stops = Stop.where({line_id: self.id})
    stations = []
    stops.each do |stop|
      station = Station.find(stop.station_id)
      stations << station.station_name
    end
    stations
  end
end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :station_name, presence: true
  has_many :stops
  has_many :lines, through: :stops

def show_lines
  lines = Stop.where({station_id: self.id})
  lines = []
  stops.each do |stop|
    line = Line.find(stop.line_id)
    lines << line.line_number
  end
  lines
 end
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :line
  belongs_to :station
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def index
    @lines = Line.all
    @line = Line.new
    @stations = Station.all
    @station = Station.new
    @stop = Stop.new
    @stops = Stop.all
  end


  def create
    @line = Line.create(line_params)
    @line.stops.create(stop_params)

    if @stop.save
      flash[:notice] ="Stop created"
      redirect_to('/stops')
    else
      render('/stops')
    end
    if @line.save
      flash[:notice] = "Bus line created."
      redirect_to('/lines')
    else
      render('/lines')
    end
  end

  def show
    @line = Line.find(params[:id])
    @stops = @line.stops
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(line_params)
      flash[:notice] = "Bus line edited"
      redirect_to('/lines')
    else
      render('/lines')
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = "Line deleted."
    redirect_to lines_path
  end

private
  def line_params
    params.require(:line).permit(:line_number)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
    @station = Station.new
  end

  def create
    @station = Station.create(station_params)
    if @station.save
      flash[:notice] ="Bus station station."
      redirect_to('/lines')
    else
      render('/stations')
    end
  end

  def show
    @station = Station.find(params[:id])
  end

  def edit
    @station = Station.find(params[:id])
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = "Station deleted."
    redirect_to lines_path
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(station_params)
      flash[:notice] = "bus station edited"
      redirect_to('/lines')
    else
      render('/lines')
    end
  end

private
  def station_params
    params.require(:station).permit(:station_name)
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController

  def index
    @stops = Stop.all
    @stations = Station.new
    @station = Station.new
  end

  def create
    @stop = Stop.create(stop_params)
    if @stop.save
      flash[:notice] ="Stop created"
      redirect_to('/stops')
    else
      render('/stops')
    end
  end

  def show
    @stop = Stop.find(params[:id])
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    flash[:notice] = "Stop deleted."
    redirect_to stops_path
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(stop_params)
      flash[:notice] = "stop edited"
      redirect_to('/stops')
    else
      render('/stops')
    end
  end

private
  def stop_params
    params.require(:stop).permit(:station_id, :line_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BusTimetable" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>



    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">

          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <div class="form-group">
    <%= f.label :line_number %>
    <%= f.text_field :line_number %>
  </div>
  <%= form_for(@stop) do |f| %>
    <div class="form-group">
      <%= f.label "Stop" %>
      <%= f.collection_select :station_id, Station.all, :id, :station_name %>
    </div>
   <% end %>
  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/lines/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/lines/index.html.erb
<h1>Create a Station</h1>
<% @stations.each do |station| %>
  <%= link_to "#{station.station_name}", station_path(station) %></br>
<% end %>

<%= content_for(:title, "New Station | Bus Timetable") %>

<%= render './stations/form' %>

<p>----------------------------------------------------------------</p>



<h1>Create a Line</h1>
<% @lines.each do |line| %>
<%= link_to "#{line.line_number}", line_path(line) %></br>
<% end %>

<%= content_for(:title, "New line | Bus Timetable") %>

<%= render 'form' %>

app/views/lines/show.html.erb
<h1>Bus #<%= @line.line_number %></h1>

<h2>Stations that stop at Line <%= @line.line_number %></h2>

<ul>
<% @line.show_stops.each do |station| %>
 <li> <%= station %></li>
<% end %>
</ul>
</br>
<%= link_to 'Back', lines_path(@line), :class => 'btn btn-primary' %>

<%= link_to "Edit", edit_line_path(@line), :class => 'btn btn-success' %>
<%= link_to "Delete", line_path(@line),
                      :line => "You sure?",
                      :method => "delete",
                      :class => "btn btn-danger" %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <div class="form-group">
    <%= f.label :station_name %>
    <%= f.text_field :station_name %>
  </div>
  <%= f.submit(:class => 'btn btn-succes') %>
<% end %>

app/views/stations/edit.html.erb
<h1>Edit <%= @station.station_name %></h1>
<%= render 'form' %>

app/views/stations/index.html.erb
<h1>Stations</h1>

<% @stations.each do |station| %>
  <%= link_to "#{station.station_name}", station_path(station) %></br>
<% end %>

<%= content_for(:title, "New Station | Bus Timetable") %>

<%= render 'form' %>

app/views/stations/show.html.erb
<h1> Station <%= @station.station_name %></h1>

<p>Bus lines that go to this station :</p>
<% @station.show_lines.each do |line| %>
  <li><%= line %></li>
  <% end %>
</ul>
</br>


</br>
<%= link_to 'Back', lines_path(@line), :class => 'btn btn-primary' %>
<%= link_to 'Edit', edit_station_path(@station), :class => 'btn btn-success' %>
<%= link_to 'Delete', station_path(@station),
                      :line => "You sure?",
                      :method => "delete",
                      :class => "btn btn-danger" %>

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <div class="form-group">
    <%= f.collection_select :line_id, Line.all, :id, :line_number %>
  </div>
  <div class="form-group">
    <%= f.collection_select :station_id, Station.all, :id, :station_name %>
  </div>
  <%= f.submit(:class => 'btn btn-succes') %>
 <% end %>